import { NextRequest, NextResponse } from 'next/server'
import { auth } from '@/lib/auth'
import { prisma } from '@/lib/prisma'
import { Octokit } from '@octokit/rest'
import type { ApiResponse } from '@/types/config'

export async function POST(request: NextRequest) {
  try {
    const session = await auth()
    if (!session?.user?.id) {
      return NextResponse.json<ApiResponse>(
        { success: false, error: 'Unauthorized' },
        { status: 401 }
      )
    }

    const { appId } = await request.json()

    const app = await prisma.app.findFirst({
      where: { id: appId, userId: session.user.id },
      include: { records: { take: 5 } }
    })

    if (!app) {
      return NextResponse.json<ApiResponse>(
        { success: false, error: 'App not found' },
        { status: 404 }
      )
    }

    const token = process.env.GITHUB_EXPORT_TOKEN
    if (!token) {
      return NextResponse.json<ApiResponse>(
        { success: false, error: 'GitHub export token not configured' },
        { status: 500 }
      )
    }

    const octokit = new Octokit({ auth: token })
    const config = app.config as Record<string, unknown>
    const repoName = `appforge-${app.name.toLowerCase().replace(/[^a-z0-9]/g, '-')}-${Date.now().toString(36)}`

    // Create repo
    const { data: repo } = await octokit.repos.createForAuthenticatedUser({
      name: repoName,
      description: `Generated by AppForge — ${app.name}`,
      auto_init: false,
      private: false,
    })

    const configJson = JSON.stringify(config, null, 2)
    const sampleData = JSON.stringify(app.records.map(r => r.data), null, 2)

    // README
    const readme = `# ${app.name}

> Generated by [AppForge](https://appforge.vercel.app) — a metadata-driven application runtime

## About this app

This is a **${(config.entity as string) || 'Item'}** management application generated from a JSON configuration.

## Config

\`\`\`json
${configJson}
\`\`\`

## Sample Data

\`\`\`json
${sampleData}
\`\`\`

## Deploy to Vercel

[![Deploy with Vercel](https://vercel.com/button)](https://vercel.com/new/clone?repository-url=https://github.com/${repo.full_name})

## Built with

- Next.js 15
- TypeScript  
- Prisma + PostgreSQL
- Generated by AppForge
`

    // Files to create
    const files = [
      { path: 'README.md', content: readme },
      { path: 'appforge.config.json', content: configJson },
      { path: 'data/sample.json', content: sampleData },
      { path: 'package.json', content: JSON.stringify({ name: repoName, version: '0.1.0', private: true, scripts: { dev: 'next dev', build: 'next build', start: 'next start' }, dependencies: { next: '^15.0.0', react: '^18.0.0', 'react-dom': '^18.0.0' }, devDependencies: { typescript: '^5.0.0', '@types/react': '^18.0.0' } }, null, 2) },
    ]

    // Create all files
    for (const file of files) {
      await octokit.repos.createOrUpdateFileContents({
        owner: repo.owner.login,
        repo: repoName,
        path: file.path,
        message: `feat: add ${file.path}`,
        content: Buffer.from(file.content).toString('base64'),
      })
    }

    return NextResponse.json<ApiResponse>({
      success: true,
      data: {
        repoUrl: repo.html_url,
        repoName: repo.full_name,
        filesCreated: files.length,
      }
    })

  } catch (error) {
    console.error('GitHub export error:', error)
    return NextResponse.json<ApiResponse>(
      { success: false, error: 'Export failed — check your GitHub token' },
      { status: 500 }
    )
  }
}
